### ISSUE TITLE
pino interface module

### ISSUE THREAD

**Issue by jsumners** [mcollina/pino#110]
Given the result of #105, should a `pino-interface` module be created that is literally nothing more than?:

```js
'use strict'

function noop () {}

module.exports = {
  fatal: noop,
  error: noop,
  warn: noop,
  info: noop,
  debug: noop,
  trace: noop,
  flush: noop,
  child: noop
}
```

Projects that are meant to be included in other projects, e.g. `Sequelize`, would then be able to do something like:

```js
function Instance (options) {
  this.log = (options.logger) ? options.logger : require('pino-interface')
}

Instance.prototype.foo = function () {
  this.log.trace('Instance.foo has been invoked')
}
```

**Comment by mcollina** [comment]
I'm thinking more of a `abstract-logging`, similar to https://www.npmjs.com/package/abstract-blob-store and https://www.npmjs.com/package/abstract-leveldown.

**Comment by jsumners** [comment]
Then should `abstract-logging` omit the `child` and `flush` methods?

**Comment by mcollina** [comment]
I think so, yes.

**Comment by jsumners** [comment]
https://github.com/jsumners/abstract-logging now exists.
