### ISSUE TITLE
deep interpolation could be faster

### ISSUE THREAD

**Issue by davidmarkclements** [mcollina/pino#14]
bole is beating pino for deep object interpolation:

benchBunyanInterpolateDeep*10000: 3725.405ms
benchWinstonInterpolateDeep*10000: 14540.212ms
benchBoleInterpolateDeep*10000: 4431.450ms
benchPinoInterpolateDeep*10000: 5358.517ms

**Comment by mcollina** [comment]
Deep object interpolation meaning? A really big JS object? Is that truly a use case? At that scale, we can hardly be significantly faster (there is a lot of stuff to move), and we are down to JSON.stringify.

Both bunyan and bole beat pino.

Anyway, does https://github.com/mcollina/pino/pull/15 fix this?

**Comment by davidmarkclements** [comment]
Heres the deep obj https://github.com/mcollina/pino/blob/master/benchmarks/multiArg.js#L11

#15 doesn't fix

**Comment by davidmarkclements** [comment]
I guess my point is, if bole and bunyan are faster for this, then why can't pino be as fast (unless we're making some kind of explicit trade off)

**Comment by mcollina** [comment]
Here is my understanding what it is happening:

* we allocate a partial output (smallish) and then we stringify all arguments, and concatenate all of this. We allocate a lot of strings, that we might need to collect.
* bunyan creates a new JS object, and then serializes it to JSON, allocating _less_ strings.
* we use two different libraries for "safe" stringifying, so it might be that bunyan's is faster.

**Comment by davidmarkclements** [comment]
the in essence, the theory is that stringify is faster for large objects vs. string collection? 

hmm, if that is the case we're stuck there, since detecting whether an object is large would become a bottleneck

we're using fast-safe-stringify in pino.js - quick-format also uses fast-safe-stringify - what other safe stringify lib are we using?

**Comment by davidmarkclements** [comment]
also - what if we allocate buffers (or ArrayBuffers) instead of strings?

**Comment by davidmarkclements** [comment]
also would cork/uncork benefit this case?

**Comment by mcollina** [comment]
Possibly, yes. We might want to try to issue two separate writes instead of
concatenating.
Il giorno lun 4 apr 2016 alle 14:14 David Mark Clements <
notifications@github.com> ha scritto:

**Comment by davidmarkclements** [comment]
If you're logging a deep object, you know you are.

So, `logger.deep.info(deepObject)`  <-- JSON.stringify the deep object

**Comment by mcollina** [comment]
I like the idea, not sure how the implementation will look like. Maybe flatstr helps and solve this issue for us.

**Comment by davidmarkclements** [comment]
I tested that, it gives a 3% increase :(

**Comment by davidmarkclements** [comment]
this is now the last piece for a totally awesome logger. 

The deep object in the benchmarks accidentally had circular references, which skewed our numbers 

The situation is actually worse than we thought:

```
benchBunyanInterpolateDeep*10000: 4419.056ms
benchWinstonInterpolateDeep*10000: 15263.350ms
benchBoleInterpolateDeep*10000: 4849.581ms
benchPinoInterpolateDeep*10000: 11768.594ms
benchPinoUnsafeInterpolateDeep*10000: 3308.311ms
benchPinoExtremeInterpolateDeep*10000: 11796.496ms
benchPinoUnsafeExtremeInterpolateDeep*10000: 3290.613ms
```

So when using just JSON.stringify (unsafe mode) we get it done in 3s,
however, fast-safe-stringify isn't to blame here, if we switch fast-safe-stringify with json-stringify-safe out figures shoot up from 11s to 25s. 

I have an experimental logger.deep.info function that converts the object using json-safe-stringify prior to passing it through for interpolation, and the results are the same. 

So like you say it may still be the string concat of a large string (resulting from stringify of large object) that's causing the issue, we need to do more research

**Comment by mcollina** [comment]
I think the problem is in quick-format. `bole` uses `util.format`, which does not have the performance issue.

However, I am not concerned at all about interpolating large objects: it's completely bad practice and generally a bad idea.

**Comment by davidmarkclements** [comment]
but our "large" object isn't really that big, and this performance degradation could be linear (hence slower results in express logger??)

**Comment by davidmarkclements** [comment]
if we take quick-format out of the equation, and directly log the deep object we get similar results:

```
benchBunyanObj*10000: 6213.428ms
benchWinstonObj*10000: 14923.850ms
benchBoleObj*10000: 24974.653ms
benchPinoObj*10000: 10242.400ms
benchPinoUnsafeObj*10000: 3006.061ms
benchPinoExtremeObj*10000: 10414.991ms
benchPinoUnsafeExtremeObj*10000: 2890.852ms
```

quick-format is adding ~1s to the 10s

**Comment by mcollina** [comment]
Ooh, is the circular reference problem then. Unsafe makes it faster. I will
look in how bunyan solves this problem.
Il giorno mer 6 apr 2016 alle 15:40 David Mark Clements <
notifications@github.com> ha scritto:

**Comment by davidmarkclements** [comment]
There arent any circular references anymore? The circular references were skewing results before becauseit meant we weren't traversing the nested objects

**Comment by mcollina** [comment]
I mean, it's the safety check to avoid the circular reference that is
slowing us down. That's what unsafe removes, and with unsafe we are faster.
Il giorno mer 6 apr 2016 alle 19:23 David Mark Clements <
notifications@github.com> ha scritto:
