### ISSUE TITLE
Child loggers do not support `.child()`

### ISSUE THREAD

**Issue by jsumners** [mcollina/pino#19]
In bunyan, loggers created from `logger.child()` also have a `.child()` method. It'd be nice to support this so that pino is mostly a drop-in replacement for bunyan.

**Comment by mcollina** [comment]
I thought almost no-one was creating child loggers of child loggers. What's your usecase?
Pino is heavily optimized, so we need to balance features with speed.

**Comment by jsumners** [comment]
Application I'm writing is modular. When it loads a module it passes in a child logger. Said module may decide to create it's own child logger from that one in order to provide further specificity.

**Comment by davidmarkclements** [comment]
@jsumners - it's a coming :bowtie:

**Comment by jsumners** [comment]
@davidmarkclements awesome. Thank you.
