### ISSUE TITLE
Formatting crashes if it gets `undefined` for a JSON parameter

### ISSUE THREAD

**Issue by jsumners** [mcollina/pino#27]
```javascript
pino.info('some %s: %j', 'object', undefined); // go boom
```

![2016-04-11_14-46-41](https://cloud.githubusercontent.com/assets/321201/14438478/5d001a98-fff4-11e5-9984-d4b58c27b2ac.png)

This occurs in a rather special situation in my application, but it seems to me like this is something logger should handle gracefully.

**Comment by davidmarkclements** [comment]
fix published as minor patch to quick-format - thanks @jsumners!

just for reference: 

pino.info('%d', undefined) will be '%d'
pino.info('%s', undefined) will be 'undefined'
pino.info('%j', undefined) will be '%j'
pino.info('%d', null) will be '%d'
pino.info('%s', null) will be 'null'
pino.info('%j', null) will be 'null'
