### ISSUE TITLE
Upload to ElasticSearch

### ISSUE THREAD

**Issue by mcollina** [mcollina/pino#34]
Similar to #33 but for the ELK stack.

**Comment by megastef** [comment]
Funny,  I've made an Elasticsearch client with bulk inserts and re-transmission/buffer (on disk) when transmission fails. Just thinking about a separate wrapper as transport module for pino.
https://github.com/sematext/logsene-js  
In case you read the docs, the TOKEN described there is actually the elasticsearch index.
