### ISSUE TITLE
Provide a way to access the loglevel as a number.

### ISSUE THREAD

**Issue by satazor** [mcollina/pino#36]
I have some piece of code that I want only to be run if the log level is >= info. This might be akward at first but consider that I want to log the progress of some huge task that requires looking some stuff into the DB and possibly other sources:

```js

function statProgress(npmNano, npmsNano) {
    // Do nothing if loglevel is gte than info
   // TODO: this won't work, pino doesn't supply getting the log level as number
    if (log.levels[log.level] < log.level.stat) {
        return;
    }

    const blacklistCount = Object.keys(config.blacklist).length;
    let pending = false;

    setInterval(() => {
        if (pending) {
            log.info('Progress stat is still being retrieved..');
            return;
        }

        pending = true;

        Promise.props({
            npmDocsCount: npmNano.infoAsync().then((res) => res.doc_count - blacklistCount),
            npmDesignDocsCount: npmNano.listAsync({ startkey: '_design/', endkey: '_design0' }).then((res) => res.rows.length),
            npmsModulesCount: npmsNano.viewAsync('npms-analyzer', 'modules-evaluation', { reduce: true }).then((res) => res.rows[0].value),
        })
        .finally(() => { pending = false; })
        .then((result) => {
            const analysis = `${(result.npmsModulesCount / (result.npmDocsCount - result.npmDesignDocsCount) * 100).toFixed(4)}%`;

            log.info({ analysis }, 'Progress stat');
        }, (err) => {
            log.error({ err }, 'Progress stat failed');
        })
        .done();
    }, 15000)
    .unref();
}
```

Obviously I don't want to be querying the DB if the loglevel is >= info. I know I can compare with strings, but I have to do 3 comparisons and is not "future" proof.

**Comment by davidmarkclements** [comment]
I don't see a reason not to do this, and you present a fair case

@mcollina thoughts?

**Comment by mcollina** [comment]
I'm ok with this change. How should we expose it? Make "level" return a number? Introduce a new property?

**Comment by jsumners** [comment]
The `Pino` prototype already has a private-by-convention `_getLevel`. Why not just make it public?

**Comment by mcollina** [comment]
@jsumners that's what gets called when you call `instance.level`: https://github.com/mcollina/pino/blob/master/pino.js#L94-L119.

Currently that's what returns the name of the level, and not the number.

Maybe we should do:

```js
instance.levelAsNumber
```

Does that make sense?
Or something prettier?

**Comment by jsumners** [comment]
I see now that `nums` is a reverse mapping of `level` (`int => str` instead of `str` => `int`). I simply looked at the `_getLevel` method and assumed `nums` was literally the number representations of the levels.

Maybe?
```javascript
Object.defineProperty(insance, 'integer', {
  get: () => levels[this._getLevel()],
  set: function() {}
});
```

**Comment by mcollina** [comment]
The arrow function won't work, but yes, that's
the general idea. How about levelInteger?

**Comment by mcollina** [comment]
Would you mind in sending a PR?

**Comment by satazor** [comment]
Yea I can, do you all agree with levelInteger? or levelNumber?

**Comment by jsumners** [comment]
I submitted it as pull request #37.

**Comment by satazor** [comment]
Ah great.

**Comment by davidmarkclements** [comment]
@satazor this is done! 👯  #39 (thanks @jsumners!)

**Comment by satazor** [comment]
Thanks everyone!
