### ISSUE TITLE
Add help to CLI

### ISSUE THREAD

**Issue by satazor** [mcollina/pino#38]
I've tried to do `pino -h` to list options but it doesn't work. `pino -v` to print the version would also be useful.

**Comment by davidmarkclements** [comment]
hey @satazor 2.2.2 published with help and version :grin:

**Comment by satazor** [comment]
Thanks @davidmarkclements, @mcollina and everyone for `pino`. Awesome module with great maintenance.

**Comment by mcollina** [comment]
Thanks @satazor!!
