### ISSUE TITLE
README is confusing on the constructor usage

### ISSUE THREAD

**Issue by rprieto** [mcollina/pino#49]
The README at https://www.npmjs.com/package/pino#constructor says `pino([stream], [opts])`. I thought this meant we can call `pino(process.stdout, {extreme: true})`. However that doesn't work, which makes sense when we look at the code:

```js
function pino (opts, stream) {
  if (opts && opts._writableState) {
    stream = opts
    opts = null
  }
}
```

Should the README say `pino([opts], [stream])` (reversed)?

**Comment by mcollina** [comment]
Thanks, fixed!
