### ISSUE TITLE
feature request: way to disable logging via environment variable 

### ISSUE THREAD

**Issue by psnider** [mcollina/pino#52]
When I run my test suites (using mocha), the test report output is cluttered with log lines.

Is there a way to turn logging off without modifying my code or configuration?
I also don't see a way to disable pino programmatically, e.g. via pino.level.

What I'm looking for is a way to set the log level via an environment variable, including a way to disable logging entirely. For example:
```
PINO_LEVEL='disabled'
```
or
```
PINO_LEVEL='error'
```

I think this could be useful for testing generally, allowing me to change the logging level on an ad-hoc basis without changing code or configuration.

**Comment by mcollina** [comment]
regarding disabling, you are right.

Try:

```js
log.levelVal = 100
```

to disable.

I'm not keen on looking into global envs, but definitely there should be an easy way to disable pino programmatically.

**Comment by psnider** [comment]
I understand not wanting to use an environment variable, 
but I don't know any other way to do this in an ad-hoc manner.
I have many modules that use pino, and don't want to modify them all.

Is there some way to change the log level across modules, perhaps using child loggers?
I couldn't figure out how to do this.

**Comment by mcollina** [comment]
@psnider if you change the log level in the parent, _before_ creating the children, that will be inherited.

**Comment by mcollina** [comment]
You can now do:

```js
pino({
  enabled: !!process.env.NOLOG
})
```

to disable logging, that should be good :)

**Comment by psnider** [comment]
Thanks, works well in 2.5.0

**Comment by pajtai** [comment]
If using `dotenv` all `process.env` variables come over as strings, so it'd have to look something like:

```javascript
pino({
    enabled: ! (process.env.LOG_ENABLED === 'false')
});
```

**Comment by normancarcamo** [comment]
Thanks I was about to ask the same but I read the docs and I end up using "silent" as level and all good.

**Comment by koenpunt** [comment]
> If using `dotenv` all `process.env` variables come over as strings

This is true for all env variables, not only when using dotenv ;)

**Comment by SeedyROM** [comment]
https://github.com/pinojs/pino/blob/master/docs/api.md#loggerlevel-string-gettersetter

There is also a level called silent!

**Comment by kohtala** [comment]
The silent level came with #266 after the enabled was added. Nice to have it mentioned here for those who are looking for it.
