### ISSUE TITLE
Typescript declaration file now on DefinitelyTypes

### ISSUE THREAD

**Issue by psnider** [mcollina/pino#62]
FWIW, I've just pushed a Typescript declaration file for pino to the Typescript community repository at:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/pino/pino.d.ts

I did my best to make sure it describes the public interface accurately.

If you find anything you would like me to change, let me know.

**Comment by mcollina** [comment]
great @psnider! Can you send a PR for the badge? I'm happy to include that here.

I'm a bit concerned about:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/pino/pino.d.ts#L17-L61

those serializers are _just_ functions, not interfaces.

**Comment by psnider** [comment]
I described the shape of the returned values since they're documented in the main README.
But looking over the docs, it seems that these could be changed to return any type that a user might want. If so, then I can change the types to:
```
    interface Serializers {
        req?: (req: any) => any
        res?: (res: any) => any
        err?: (error: Error) => any
    }
```

Using this declaration, TypeScript will only be checking spelling of req, res, err, and that these occur in the correct containing objects.

See [TypeScript interfaces](https://www.typescriptlang.org/docs/handbook/interfaces.html).

**Comment by psnider** [comment]
What is the badge?
If it is for the github README, I won't be able to add one, as the community repository, [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), contains declarations for about 2000 npm packages, and is managed by the curators.

**Comment by mcollina** [comment]
@psnider yes, that's what I meant.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/pino/pino.d.ts#L110, why are you specifying `{}` instead of `any`? (I'm just curious, the interface seems ok).

Another project of mine got a badge: https://github.com/mqttjs/MQTT.js/pull/386.

**Comment by psnider** [comment]
> ```{}``` vs ```any```

I understood that the optional first argument is an object, in which case ```{}``` should be used.
I any type at all can be used, then I should change these to ```any```.

**Comment by mcollina** [comment]
Yes, it's an object, thanks! :)

**Comment by mcollina** [comment]
Merged!

**Comment by psnider** [comment]
I've updated the declaration file on DefinitelyTyped to include the above change:
```
    interface Serializers {
        req?: (req: any) => any
        res?: (res: any) => any
        err?: (error: Error) => any
    }
```

**Comment by rundef** [comment]
Hi,
I think I might have found a small bug in the TypeScript definition, see here : https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11057

**Comment by evanshortiss** [comment]
@psnider I've updated TS typings. Your input is appreciated https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12850
