### ISSUE TITLE
Support injecting serializers via .child()

### ISSUE THREAD

**Issue by mcollina** [mcollina/pino#66]
Currently it is not possible to add serializers in child loggers.

See https://github.com/mcollina/pino/pull/57 as an example of how it could be implemented.

**Comment by dgonzalez** [comment]
Quick question, should a serializer added to the child replace the existing ones from the parent or should it be added to the existing ones? (as far as I am aware it is an array). I might be able to work on this today/weekend.

**Comment by mcollina** [comment]
it should be added to the existing ones, but just for that child logger.
