### ISSUE TITLE
Extreme mode timeout for flushing

### ISSUE THREAD

**Issue by dgonzalez** [mcollina/pino#72]
Hi, I was reading about the extreme mode and I think it is a really good idea. I also think adding a flush timeout would help to prevent some of the potential data loss:
- The buffer keeps saving data until one of those things happen:
     - It reaches the limit (4k)
     - A timeout flushes the cache into the output stream if it hasn't been flushed before.

Kafka does that on the producer and seems to be the most optimal way of handling a high throughput data ingestion stream. Any thoughts?

Also flushing the cache on extreme mode when a termination signal is sent to the process would prevent from data being lost (I don't think it is happening right now).

**Comment by mcollina** [comment]
Some notes (we might improve the readme on that):

* extreme mode is built for processes doing _crazy_ amount of logging, where 4KB are nothing and gets flushed multiple time a second.
* rescheduling timers is _slow_, we can use https://www.npmjs.com/package/retimer to mitigate it, but I would prefer not to do it at all.
* I'm 👍  on adding a simple way (see #42) to `flush()` given a signal, but I won't put it in pino, as an app might want to handle that signal differently.
* The data is flushed on exit, see https://github.com/mcollina/pino/blob/master/pino.js#L368-L374.

Would you like to send a PR against the README?

**Comment by dgonzalez** [comment]
I missed the flush on exit (I actually need to read and understand the `handle` function). I will be trying to do some work on pino today so documenting the flush seems like a needed thing :dancer:.

**Comment by davidmarkclements** [comment]
We still need to document the flush function

**Comment by dgonzalez** [comment]
On it.
