### ISSUE TITLE
How to Write Multiple Streams Similar to Bunyan

### ISSUE THREAD

**Issue by dtothefp** [mcollina/pino#80]
In Bunyan I could do 

```js
const streams = [
  {
    level: 'warn',
    path: path.join(LOG_DIRECTORY, `${APP_NAME}-warn.log`)
  },
  {
    level: 'error',
    path: path.join(LOG_DIRECTORY, `${APP_NAME}-error.log`)
  }
);

const logger = buyan.createLogger({
  name: APP_NAME,
  streams,
  serializers: bunyan.stdSerializers
});
```

Looks like in `pino` with the `stream` argument it is only possible to write to a single stream and log level per logger instance? Is there a simple way to mimic this Bunyan behavior?

**Comment by dtothefp** [comment]
I hacked around this by creating multiple Pino instances. Seems sloppy, wondering if there is a better way?

```js
const serializers = pino.stdSerializers;
const name = APP_NAME;

if (LOG_ENV === 'development' || NODE_ENV === 'development') {
  const pretty = pino.pretty();

  pretty.pipe(process.stdout);

  logger = pino({
    name,
    level: 'info',
    serializers
  }, pretty);
} else {
  const noop = arg => arg;
  const streams = [
    {
      level: 'warn',
      path: path.join(LOG_DIRECTORY, `${APP_NAME}-warn.log`)
    },
    {
      level: 'error',
      path: path.join(LOG_DIRECTORY, `${APP_NAME}-error.log`)
    }
  ];

  logger = streams.reduce((acc, data) => {
    const {level, path: logPath} = data;
    const writeStream = fs.createWriteStream(logPath, {
      flags: 'a',
      encoding: 'utf8'
    });
    const inst = pino({
      name,
      level,
      serializers
    }, writeStream);

    acc[level] = inst[level].bind(inst);

    return acc;
  }, {});

  logger.info = noop;
}
```

**Comment by davidmarkclements** [comment]
Hi @dtothefp 

The "pino way" is to avoid any in-process overhead - only having one output stream is entirely deliberate - any other log processing should be done out-of-process

So what we'd need is

```sh
node app.js | pino-split-by-log-type 
```

This ties into https://github.com/mcollina/pino#how-to-use-transports-with-pino

Currently, we don't have `pino-split-by-log-type`, but if you're up for building it, here's some transports you can take inspiration from 

* https://www.npmjs.com/package/pino-syslog
* https://www.npmjs.com/package/pino-elasticsearch
* https://www.npmjs.com/package/pino-socket

Let me know if you'd like to build it, and I'll support you (just open issues on your own repo and cc me (and Matteo) and we'll give feedback etc)

**Comment by dtothefp** [comment]
@davidmarkclements thanks for the tips, if I get some time I will definitely try to work on this

**Comment by mcollina** [comment]
@dtothefp side note, you should really _not_ use `bind`, it is super slow. Wrap the other call inside a function.

**Comment by dtothefp** [comment]
@mcollina good call, didn't know `bind` was slower
