### ISSUE TITLE
Modifying the format (or pattern) of the logs

### ISSUE THREAD

**Issue by lucykang** [mcollina/pino#81]
Is it possible to modify the format or pattern of the logs? For example, instead of having the date first, I would like it to print the log level first.

**Comment by mcollina** [comment]
In the pretty converter? I don't see why not, would you like to send a PR to introduce a flag?

**Comment by colm-mcqs** [comment]
@mcollina I fired up a PR there to flip level and time around. 

The flag could probably have a better name than `levelFirst` though...

**Comment by lucykang** [comment]
@colm-mcqs Sorry for late reply. Thank you!
