### ISSUE TITLE
Can't log to stderr in tricky case

### ISSUE THREAD

**Issue by krazylek** [mcollina/pino#85]
Hello Matteo,

While playing with pino, I noticed a subtle bug, when stderr is redirected from bash like this:
```
node index.js 2> error.log
```
And *index.js* looks like
```
var pino = require('pino')
var log = pino(process.stderr)
log.warn('will output to stdout')
```

It seems related to the property `_writableState` which is `undefined` in this case.

So the condition `opts && opts._writableState` to assign opts to the stream, can't pass.

Note that it just happens when options are omitted!

Cheers,
Benoit

**Comment by davidmarkclements** [comment]
Very nice catch
